-- ─────────────────────────────────────────────────────────────────────────────
-- HELD — DO NOT APPLY WITHOUT MYKE SIGN-OFF.
--
-- This seeds the Briefing Library token meter. Setting a product_meter value is an
-- ALWAYS-HUMAN action per FAR-56 (pricing / token-pack / product-meter changes) and is
-- owned by FAR-46 (the meter lock). The prompt is explicit: "Do not change the meter
-- value in code — it is product_meters['briefing_library'], Myke-governed."
--
-- DISCREPANCY TO RESOLVE (flag for Myke):
--   • The existing `product_meters` row `briefing` = 5 tokens (FAR-16/FAR-46 draft).
--   • This storefront brief sets the Briefing LIBRARY unit at 10 tokens.
--   These are plausibly distinct products (a single "Briefing" unlock vs a Library
--   acquisition), but the numbers must be reconciled before commerce-on.
--
-- Until this row exists, library_checkout() returns {error: 'meter_unset'} and the
-- commerce-on flag stays OFF — the storefront degrades safely.
-- ─────────────────────────────────────────────────────────────────────────────

-- insert into public.product_meters (product_key, display_name, tokens_cost, free, status)
-- values ('briefing_library', 'Briefing Library', 10, false, 'draft')
-- on conflict (product_key) do update set tokens_cost = excluded.tokens_cost, status = 'draft', updated_at = now();
--
-- FAR-46 flips status → 'final' once the margin calculus signs off the value.
